# params.yaml
prepare:
  random_seed: 42

features:
  test_size: 0.2
  random_state: 42

train:
  n_estimators: 200
  max_depth: 12
  random_state: 42

evaluate:
  metrics: [r2, mae, rmse]